### PR TITLE
Base project update

### PR DESCRIPTION
**Pull request by nzaitz**
Restructured beans to match new ERD, some additional beans created and added for Cognito functionality, Admin service completed.

### CODE REVIEW

**Review by Kairn — CHANGES_REQUESTED** [review]
There are lots of styles and naming conventions and other related issues that need to be addressed before the merge can happen, check DocStyleBug folder in the google drive for complaints. And also there are too many files that get changed for one pull request, try to limit to 5-7 files.

**Comment by nzaitz** [comment]
I'll look at the style guidelines, but there are not too many files, emily
told us specifically the initial merge was going to be larger so you can
talk to her about it.

**Comment by caxmouch** [comment]
Confirming that initial merge will be large. @Kairn it might be more efficient to provide examples of specific grievances against conventions here. @nzaitz lemme know when you've refactored.

**Comment by nzaitz** [comment]
Will do.

**Comment by Kairn** [comment]
I think we still need to talk tomorrow before any merge can happen

**Comment by caxmouch** [comment]
I'm all for tidiness, but I don't want merging to turn into a bottleneck for the sake of unnecessary perfection.

**Comment by Kairn** [comment]
most of the naming convention complaints are simply friendly suggestions on my end to keep things consistent, if you think it requires to much refactoring for certain variable names, then you don't have to change it but just be extra careful in the future

**Comment by nzaitz** [comment]
Eddy, I understand your concerns but if you are going to keep railroading
us over minor styling issues which can be easily corrected we are going to
run out of time on this project. My concerns right now lie with getting the
project in a functional state before the deadline in a week. More
constructive or useful input from you if you are going to hold us up every
time we go to merge would be greatly appreciated.

On Jan 24, 2019 21:17, "Eddy Soma" <notifications@github.com> wrote:

I think we still need to talk tomorrow before any merge can happen

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/1810Oct29SPARK/krowd-boot/pull/5#issuecomment-457431149>,
or mute the thread

**Comment by Kairn** [comment]
I said everything that needs to be said. So if you guys all feel comfortable, then go ahead and merge the request

**Pull request merged**
